pipeline {
    agent {
        docker {
            image 'node:latest'
            args '-p 8081:8081'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Serve') {
            steps {
                sh 'npm run serve'
            }
        }
    }
}
